Moves call to `RateParameter.check_values` to `Fit.__init__`.
With this method called in `RateParameter` constructor, it was causing:
```
ValueError: Prior not in values array. This can be achieved with an odd number of bins and symmetric low and high values about the prior.
```
to be raised in store.py line 160.